---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
      - test/**/*
  eslint:
    enabled: true
    checks:
      global-require:
        enabled: false
      no-new-func:
        enabled: false
      no-unused-expressions:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- coverage/
- demo/
- dist/
- doc/
- node_modules/
- vendor/
- test/runner.js
- gulpfile.js
