---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_paths:
      - test/**/*
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- coverage/
- demo/
- dist/
- doc/
- node_modules/
- test/
- vendor/
